# **Table of Contents**
* [Array creation](#section_1)
* [Range , Arange](#section_2)
* [Access](#section_3)
* [Operations](#section_4)
* [Math functions](#section_5)
* [Zeros & Ones](#section_6)
* [3D matrix](#section_7)
* [Dot product](#section_8)
* [Random Num](#section_9)
* [Linspace](#section_10)
* [Maximum , Minimum](#section_11)
* [Any , All](#section_12)
* [Null](#section_13)
* [Where](#section_14)
* [Iteration](#section_15)
* [Stack](#section_16)
* [Broadcast](#section_17)
* [Copy](#section_18)
* [Block](#section_19)
* [Concatenate](#section_20)

In [1]:
import numpy as np

<a id='section_1'></a>
# 1. **Array Creation**

### 1D

In [2]:
ls  = [1,2,3,4]

arr = np.array(ls)
arr

array([1, 2, 3, 4])

In [3]:
arr.ndim

1

In [4]:
arr.shape

(4,)

### 2D

In [5]:
ls1 = [1,2,3,4]
ls2 = [10,20,30,40]

ls  = [ls1 , ls2]

a   = np.array(ls)
a

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [6]:
a.ndim

2

In [7]:
a.shape

(2, 4)

In [8]:
a.dtype

dtype('int32')

<a id='section_2'></a>
# 2. **Range , Arange**

### **Range**

In [9]:
list (range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
list (range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
list (range(1,10,2))

[1, 3, 5, 7, 9]

### **Arange**

In [12]:
np.arange (10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange (1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange (1,10,2)

array([1, 3, 5, 7, 9])

### arange + reshape

In [15]:
np  .arange(2,21,2)  .reshape(5,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

<a id='section_3'></a>
# 3. **Access**

In [16]:
a  =  np.arange(1,51).reshape(5,10)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

**Fetch Element**

In [17]:
a [0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a [-1]

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [19]:
a [0,0]

1

In [20]:
a [0][0]   # not preferred

1

In [21]:
a [-1,-1]

50

**Fetch wrt Row , Col**

In [22]:
a [:,1]                             # 2nd column

array([ 2, 12, 22, 32, 42])

In [23]:
a [3:5,5:8]    

array([[36, 37, 38],
       [46, 47, 48]])

**Step Size wrt Row , Col**

In [24]:
a [::2]                 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [25]:
a [:,::2]     # select all rows with step 2 for columns

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [26]:
a [::-1]   # row reverse with step 1

array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [27]:
a [: , ::-1]

array([[10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
       [20, 19, 18, 17, 16, 15, 14, 13, 12, 11],
       [30, 29, 28, 27, 26, 25, 24, 23, 22, 21],
       [40, 39, 38, 37, 36, 35, 34, 33, 32, 31],
       [50, 49, 48, 47, 46, 45, 44, 43, 42, 41]])

**Fancy Indexing**

In [28]:
a [[1,3,4]]              # extracting row index 1,5,6

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [29]:
a [ : , [1,3,4] ]        # extracting column index 1,5,6

array([[ 2,  4,  5],
       [12, 14, 15],
       [22, 24, 25],
       [32, 34, 35],
       [42, 44, 45]])

### By Condition

In [30]:
a [ a < 15 ]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

<a id='section_4'></a>
# 4. **Operations**

### Arithmetic & Relational Operations

**Single Array**

In [31]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [32]:
print (a + 2)
print (a ** 2)

[3 4 5 6]
[ 1  4  9 16]


In [33]:
print (a <  3)
print (a == 3)

[ True  True False False]
[False False  True False]


**Multiple arrays**

In [34]:
a = np.array ([10,20,30])
b = np.array ([5,15,25])

a - b

array([5, 5, 5])

In [35]:
a1 = np.array ( [ [1,2]  , [3,4]   ] )
a2 = np.array ( [ [10,20], [30,40] ] )

a3 = a1 + a2
a3

array([[11, 22],
       [33, 44]])

<a id='section_5'></a>
# 5. **Math Functions**

## 1 D

In [36]:
a = np.array ( [4,9,16,25,25] )

In [37]:
np.sqrt (a)

array([2., 3., 4., 5., 5.])

In [38]:
np.mean (a)

15.8

In [39]:
np.median (a)

16.0

In [40]:
import statistics

statistics.mode(a)

25

## 2 D

In [41]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
a.mean()         # all elements

5.0

In [43]:
a.mean(1)        # row-wise      # since axis=1

array([2., 5., 8.])

In [44]:
a.mean(0)        # column-wise   # since axis=0

array([4., 5., 6.])

In [45]:
a  =  np.arange (0,6)

np.array_split (a,2)

[array([0, 1, 2]), array([3, 4, 5])]

<a id='section_6'></a>
# 6. **Zeros & Ones**

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [48]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

For Ndim=2 , below 2 methods

In [49]:
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
a = np.zeros ( (2,3) )                   # np.zeros ((2,3))

In [51]:
print (a.shape)
print (a.size)

(2, 3)
6


In [52]:
b = np.zeros ( ((2,3,4)) )
b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Diagonal Matrix   

In [53]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<a id='section_7'></a>
# 7. **3D matrix**

In [54]:
a = np.arange(18).reshape(2,3,3)         #  to get   2 sets/layers/depths    of  3x3
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [55]:
a.shape

(2, 3, 3)

In [56]:
a.ndim     

3

<a id='section_8'></a>
# 8. **Dot product**

In [57]:
a = np.arange(1,7).reshape(2,3)       # 2x3
a

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
b = a.T                               # 3x2
b

array([[1, 4],
       [2, 5],
       [3, 6]])

3 methods

In [59]:
np.dot(a,b)

array([[14, 32],
       [32, 77]])

In [60]:
a.dot(b)

array([[14, 32],
       [32, 77]])

In [61]:
a @ b

array([[14, 32],
       [32, 77]])

<a id='section_9'></a>
# 9. **Random Num**

### **i. Rand**
uniform distribution between `[0, 1)`.

In [62]:
np.random.rand (5)

array([0.88412485, 0.33787301, 0.52394341, 0.64061952, 0.58513965])

In [63]:
np.random.rand (3,2)

array([[0.55150836, 0.90715927],
       [0.36421862, 0.23597729],
       [0.55758604, 0.58253847]])

### **ii. Randint**

In [64]:
np.random.randint  (1,101,size=5)

array([72,  5,  3,  8, 99])

In [65]:
np.random.randint  (1,101,10)

array([31, 22, 15, 32, 62, 49, 98,  5, 95, 77])

In [66]:
arr = np.random.randint (1,101,25).reshape(5,5)
arr

array([[37, 19, 38, 94, 54],
       [24, 71,  2, 26, 49],
       [64, 40, 99, 96, 35],
       [58,  7, 88, 42, 66],
       [49, 36, 17, 74, 76]])

### **iii. Randn**

* mean = 0
* std = 1

In [67]:
a = np.random.randn (50)
a

array([ 0.6250583 , -0.68586484, -0.40427186,  1.65759091,  1.15116015,
       -0.48110526, -0.7649581 ,  1.39895662,  0.16929549, -0.40476116,
        1.60745865, -0.75606118, -0.3454299 ,  1.07111446, -0.35814702,
       -0.33412371, -0.49784446, -0.51155563, -0.33836901, -1.95919655,
       -1.0641926 , -0.73684618,  0.38955443, -0.0881579 , -0.41345374,
        0.38096404,  0.47286036, -0.10712846, -0.52332784,  0.06884953,
        0.73841381,  1.43747391, -1.10568772, -0.81850742, -0.75445839,
       -0.46670484, -0.53348124, -0.80729474,  1.51310608,  2.06781182,
        0.27474564,  0.79629049,  0.89261798, -0.59727753,  1.47011784,
        1.28043318, -1.0059268 , -1.50990857, -0.38844076,  0.98571511])

In [68]:
np.random.randn (3,4)

array([[-1.23852865, -0.32761183, -0.58343145,  1.53284202],
       [ 1.20457822,  0.75019148,  1.11877676,  0.26546604],
       [ 2.12174855, -0.18900083,  1.06035856, -0.46259657]])

<a id='section_10'></a>
# 10. **Linspace**

In [69]:
np.linspace (2,3,5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

Create an array of floating point numbers from 1 to 5 with as step of 0.5

In [70]:
a4 = np.linspace ( 1.0 , 5.0 , num=10)
a4

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Create an array of numbers between 0 and 5 with the value 5 also included.

In [71]:
a5 = np.linspace (0,5,15)
a5

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

<a id='section_11'></a>
# 11. **Maximum , Minimum**

In [72]:
a  =  np.random.randint (1,101,10)
b  =  np.random.randint (1,101,10)

print (a)
print (b)

[ 33  62  11 100  17  50  53  60   9  40]
[ 1 66 87 38 89 63 86 86 52  3]


In [73]:
np.maximum (a , b)

array([ 33,  66,  87, 100,  89,  63,  86,  86,  52,  40])

In [74]:
np.minimum (a , b)

array([ 1, 62, 11, 38, 17, 50, 53, 60,  9,  3])

<a id='section_12'></a>
# 12. **Any , All**

In [75]:
a = np.array ( [True,True,True]    )
b = np.array ( [False,False,False] )
c = np.array ( [True,True,False]   )

In [76]:
print (a.all())
print (b.all())
print (c.all())

True
False
False


In [77]:
print (a.any())
print (b.any())
print (c.any())

True
False
True


<a id='section_13'></a>
# 13. **Null**

In [78]:
a = np.array ( [1,2,np.nan,np.nan,5] )

print (a)
print (a.size)

[ 1.  2. nan nan  5.]
5


<a id='section_14'></a>
# 14. **Where**

In [79]:
a = [1,2,3,4]
b = [100,200,300,400]
c = [True,False,True,False]

np.where (c,a,b)

array([  1, 200,   3, 400])

In [80]:
a = np.array ( [1,2,3,4]               ).reshape(2,2)
b = np.array ( [100,200,300,400]       ).reshape(2,2)
c = np.array ( [True,False,True,False] ).reshape(2,2)

np.where (c,a,b)

array([[  1, 200],
       [  3, 400]])

In [81]:
age = np.random.randint(1,50,10)
age

array([12, 44,  1, 39, 40, 39, 32,  3, 31, 26])

### Application 1

In [82]:
np.where ( age<=18, 19, age)                       # temp change

array([19, 44, 19, 39, 40, 39, 32, 19, 31, 26])

### Application 2

In [83]:
np.where ( age<=18 )

(array([0, 2, 7], dtype=int64),)

<a id='section_15'></a>
# 15. **Iteration**

In [84]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
c=1
for i in a:
    print("Iteration ",c,i)
    c=c+1

Iteration  1 [1 2 3]
Iteration  2 [4 5 6]
Iteration  3 [7 8 9]


In [86]:
a  =  np.array ( [ [1,2,3] , [4,5,6] , [7,8,9] ] )

for i in a:
    print(i) 

[1 2 3]
[4 5 6]
[7 8 9]


<a id='section_16'></a>
# 16. **Stack**

In [87]:
a = np.array ( [1,2,3]       )
b = np.array ( [10,20,30]    )
c = np.array ( [100,200,300] )

In [88]:
np.stack ([a,b,c])

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [89]:
np.column_stack ([a,b,c])

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300]])

In [90]:
np.hstack ([a,b,c])                                         # row stack

array([  1,   2,   3,  10,  20,  30, 100, 200, 300])

In [91]:
arr = np.dstack ([a,b,c])                                   # depth stack
arr

array([[[  1,  10, 100],
        [  2,  20, 200],
        [  3,  30, 300]]])

<a id='section_17'></a>
# 17. **Broadcast**

In [92]:
a = np.zeros (3)

a [:] = 4
a

array([4., 4., 4.])

In [93]:
a = np.zeros ((3,4))

a [:,:] = 6
a

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

<a id='section_18'></a>
# 18. **Copy**

In [94]:
a  =  np.array ([1,2,3])

b  =  a.copy()
b

array([1, 2, 3])

<a id='section_19'></a>
# 19. **Block**

* Used to join 2 or more arrays into 1 array

In [95]:
A = np.array ([1, 2, 3])
B = np.array ([4, 5, 6])
C = np.array ([7, 8, 9])

np.block ( [A, B, C , 100] )

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100])

<a id='section_20'></a>
# 20. **Concatenate**

In [96]:
arr1  =  np.arange(1,10).reshape(3,3)
arr2  =  np.arange(11,20).reshape(3,3)

In [97]:
np.concatenate ( [arr1,arr2] )                 # by default :   axis=0  &  row_stack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [98]:
np.concatenate ( [arr1,arr2] , axis=1 )          # axis=1 & col_statck

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])